tasks:
  - init: |
      docker-compose -f .devcontainer/docker-compose.yml  pull
  - command: |
      docker-compose -f .devcontainer/docker-compose.yml  up --build

ports:
  - port: 80
    onOpen: open-preview
  - port: 8081
    onOpen: ignore
  - port: 6379
    onOpen: ignore
  - port: 3306
    onOpen: ignore
