tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up

ports:
  - port: 80
    onOpen: open-preview
  - port: 8081
    onOpen: ignore
  - port: 6379
    onOpen: ignore
  - port: 3306
    onOpen: ignore
