version: '3.8'

services:
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./.devcontainer/nginx/:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb-data:
