version: '3.8'

services:

  php-fpm:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php-fpm
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/var/www/html


  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/:/var/www
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - php-fpm
